"""This module saves the cam file with the blocks that were generated by the
block_generator module."""

def save_cam(blocks, cam_file):
    """This function saves the cam file with the blocks that were generated by the
    block_generator module.
    Args:
        blocks (List[Dict]): A list of dictionaries with the data of the blocks.
        cam_file (str): The path to the cam file.
    """
    with open(cam_file, "w", encoding="utf-8") as file:
        # Writes the start of file.
        file.write("BOF\n")
        file.write("G90\n")
        for block in blocks:
            file.write(block["text"] + "\n")
        # Writes the end of file.
        file.write("M02\n")
        file.write("EOF\n")